// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/:lang/data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[lang]/data.get').default>>>>
    }
    '/api/:lang/definition/:word': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[lang]/definition/[word].get').default>>>>
    }
    '/api/:lang/word-image/:word': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[lang]/word-image/[word].get').default>>>>
    }
    '/api/:lang/word-stats': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[lang]/word-stats.post').default>>>>
    }
    '/api/languages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/languages.get').default>>>>
    }
    '/api/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stats.get').default>>>>
    }
    '/llms.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/llms.txt').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/robots.txt').default>>>>
    }
    '/sitemap-main.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap-main.xml').default>>>>
    }
    '/sitemap-words-:lang.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap-words-[lang].xml').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.2_db0@0.3.4_ioredis@5.10.0_magicast@0.5.2_nuxt@3.21.2_@parcel+w_5f6482d5f82f46663f3fe203fa79cafa/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}