"""DEPRECATED: Wiktionary plaintext parser for definition extraction.

Replaced by LLM-first architecture (March 2026).
Kept for reference and potential rollback.

This module contained the plaintext Wiktionary parser that extracted definitions
from MediaWiki API responses. It supported 65 languages with varying confidence
levels (CONFIDENT/PARTIAL/UNRELIABLE).

The parser was fragile for multi-etymology words (e.g. "greet" returned archaic
"mourning" instead of "to welcome") because it walked top-to-bottom and took
the first definition regardless of which etymology section it came from.
"""

import json
import re
import urllib.parse
import urllib.request as urlreq

# ---------------------------------------------------------------------------
# Parser confidence levels
# ---------------------------------------------------------------------------

CONFIDENT = "CONFIDENT"
PARTIAL = "PARTIAL"
UNRELIABLE = "UNRELIABLE"

# Generated by tests/test_wiktionary_parser.py — do not edit manually
PARSER_CONFIDENCE = {
    "ar": PARTIAL,
    "az": CONFIDENT,
    "bg": CONFIDENT,
    "br": UNRELIABLE,
    "ca": CONFIDENT,
    "ckb": CONFIDENT,
    "cs": CONFIDENT,
    "da": UNRELIABLE,
    "de": CONFIDENT,
    "el": CONFIDENT,
    "en": CONFIDENT,
    "eo": CONFIDENT,
    "es": CONFIDENT,
    "et": PARTIAL,
    "eu": UNRELIABLE,
    "fa": CONFIDENT,
    "fi": CONFIDENT,
    "fo": UNRELIABLE,
    "fr": CONFIDENT,
    "fur": UNRELIABLE,
    "fy": UNRELIABLE,
    "ga": UNRELIABLE,
    "gd": UNRELIABLE,
    "gl": CONFIDENT,
    "he": UNRELIABLE,
    "hr": CONFIDENT,
    "hu": CONFIDENT,
    "hy": CONFIDENT,
    "hyw": CONFIDENT,
    "ia": PARTIAL,
    "ie": UNRELIABLE,
    "is": CONFIDENT,
    "it": CONFIDENT,
    "ka": PARTIAL,
    "ko": CONFIDENT,
    "la": UNRELIABLE,
    "lb": UNRELIABLE,
    "lt": CONFIDENT,
    "ltg": UNRELIABLE,
    "lv": PARTIAL,
    "mi": UNRELIABLE,
    "mk": UNRELIABLE,
    "mn": CONFIDENT,
    "nb": CONFIDENT,
    "nds": UNRELIABLE,
    "ne": UNRELIABLE,
    "nl": CONFIDENT,
    "nn": UNRELIABLE,
    "oc": PARTIAL,
    "pau": UNRELIABLE,
    "pl": CONFIDENT,
    "pt": CONFIDENT,
    "qya": UNRELIABLE,
    "ro": CONFIDENT,
    "ru": CONFIDENT,
    "rw": UNRELIABLE,
    "sk": UNRELIABLE,
    "sl": UNRELIABLE,
    "sr": PARTIAL,
    "sv": CONFIDENT,
    "tk": UNRELIABLE,
    "tlh": UNRELIABLE,
    "tr": CONFIDENT,
    "uk": UNRELIABLE,
    "vi": CONFIDENT,
}

# Language codes where the Wiktionary subdomain differs from the game's lang code
WIKT_LANG_MAP = {"nb": "no", "nn": "no", "hyw": "hy", "ckb": "ku"}


def strip_html(text):
    """Strip HTML tags from a string."""
    return re.sub(r"<[^>]+>", "", text).strip()


def _fallback_extract_definition(extract, word=None):
    """Last-resort heuristic: grab first substantive line after any == header."""
    lines = extract.split("\n")
    after_header = False
    skip_sections = re.compile(
        r"^={2,4}\s*(Etymology|Pronunciation|Etym|Pronunc|הגייה|מקור|"
        r"References|See also|External|Anagrams|Derived|Related|Translations|"
        r"Übersetzung|Etimología|Etimologia|Étymologie|Herkunft|"
        r"Konjugierte Form|Deklinierte Form)",
        re.IGNORECASE,
    )
    for line in lines:
        line = line.strip()
        if not line:
            continue
        if re.match(r"^={2,4}\s*", line):
            after_header = not skip_sections.match(line)
            continue
        if not after_header:
            continue
        if re.match(r"^(IPA|Rhymes|Homophones|\[|//|\\)", line):
            continue
        if re.match(
            r"^(Nebenformen|Aussprache|Worttrennung|Silbentrennung|"
            r"Hörbeispiele|Reime|Grammatische Merkmale)\s*:?\s*$",
            line,
            re.IGNORECASE,
        ):
            continue
        if word and line.lower() == word.lower():
            continue
        if len(line) > 5 and len(line) < 300:
            return line[:300]
    return None


def _filter_language_section(extract, lang_code):
    """Filter a Wiktionary extract to only include the target language section."""
    LANG_SECTION_NAMES = {
        "de": "Deutsch",
    }
    lang_name = LANG_SECTION_NAMES.get(lang_code)
    if not lang_name:
        return extract

    lines = extract.split("\n")
    filtered = []
    in_target_section = False
    for line in lines:
        stripped = line.strip()
        m = re.match(r"^==\s*\S+.*?\((.+?)\)\s*==\s*$", stripped)
        if m:
            section_lang = m.group(1).strip()
            in_target_section = section_lang == lang_name
            if in_target_section:
                filtered.append(line)
            continue
        if re.match(r"^==\s*[^=]", stripped) and not re.match(r"^===", stripped):
            if in_target_section:
                break
            continue
        if in_target_section:
            filtered.append(line)

    return "\n".join(filtered) if filtered else ""


def parse_wikt_definition(extract, word=None, lang_code=None):
    """Extract a definition line from a Wiktionary plaintext extract."""
    if lang_code:
        extract = _filter_language_section(extract, lang_code)
    lines = extract.split("\n")
    in_definition_section = False

    if word is None:
        for line in lines:
            m = re.match(r"^==\s*(.+?)\s*==\s*$", line.strip())
            if m:
                word = m.group(1).strip()
                break

    defn_headers = re.compile(
        r"^={2,4}\s*("
        r"Noun|Verb|Adjective|Adverb|Pronoun|Preposition|Conjunction|Interjection|"
        r"Nom commun|Verbe|Adjectif|Adverbe|Forme de verbe|Forme de nom commun|"
        r"Sustantivo\b|Verbo|Adjetivo|Adverbio|"
        r"Forma adjetiva|Forma sustantiva|Forma verbal|"
        r"Substantivo|Sostantivo|Aggettivo|"
        r"Substantiv\w*\b|Adjektiv\w*\b|Verb\b|"
        r"Substantiivi|Adjektiivi|Verbi|Adverbi|Pronomini|"
        r"Nimisõna|Tegusõna|Omadussõna|"
        r"Daiktavardis|Veiksmažodis|Būdvardis|"
        r"Főnév|Ige|Melléknév|"
        r"Anv-kadarn|"
        r"Vèrb|"
        r"İsim|Ad\b|Eylem|Sıfat|Belirteç|"
        r"Գոյական|Բայ|Ածական|"
        r"Rengdêr|Navdêr|"
        r"Danh từ|Động từ|Tính từ|"
        r"المعاني|"
        r"Съществително|Прилагателно|Глагол|"
        r"Значение|"
        r"Bijvoeglijk naamwoord|Zelfstandig naamwoord|Werkwoord|"
        r"Imenica|Glagol|Pridjev|Prilog|"
        r"Именица|Глагол\b|Придев|Прилог|"
        r"Samostalnik|Pridevnik|"
        r"Ουσιαστικό|Ρήμα|Επίθετο|"
        r"שם עצם|פועל|שם תואר|"
        r"Adjectiv|"
        r"Podstatné jméno|Sloveso|Přídavné jméno|"
        r"Podstatné meno|Prídavné meno|"
        r"არსებითი სახელი|ზმნა|"
        r"Nom\b|Adjectiu|"
        r"Nomina|Verba|Adjektiva|"
        r"Іменник|Дієслово|Прикметник"
        r")",
        re.IGNORECASE,
    )

    defn_text_markers = re.compile(
        r"^(Bedeutungen|znaczenia|Значення|Значэнне)\s*:?\s*$", re.IGNORECASE
    )

    skip_line = re.compile(
        r"^("
        r"=|IPA|Rhymes:|Homophones:|wymowa:|Pronúncia|Prononciation|Pronunciación|"
        r"Nebenformen|Aussprache|Worttrennung|Silbentrennung|Hörbeispiele|Reime|"
        r"Étymologie|Etimología|Etimologia|Etymology|Herkunft|"
        r"Synonym|Sinónim|Sinônim|Antonym|Antónim|"
        r"Übersetzung|Translation|Tradução|Oberbegriffe|"
        r"Beispiele|Examples|Uso:|odmiana:|przykłady:|składnia:|kolokacje:|"
        r"synonimy:|antonimy:|hiperonimy:|hiponimy:|holonimy:|meronimy:|"
        r"wyrazy pokrewne:|związki frazeologiczne:|etymologia:|"
        r"Cognate |From |Du |Del |Do |Uit |Vom |Van |Derived |Compare |"
        r"rzeczownik|przymiotnik|przysłówek|czasownik|"
        r"Deklinacija|Konjugacija|Склонение|Склоненье|"
        r"תעתיק|הגייה"
        r")",
        re.IGNORECASE,
    )

    end_markers = re.compile(
        r"^(Herkunft|Synonyme|Antonyme|Oberbegriffe|Beispiele|Nebenformen|"
        r"Aussprache|Worttrennung|Silbentrennung|"
        r"Übersetzungen|odmiana|przykłady|składnia|kolokacje|"
        r"synonimy|antonimy|wyrazy pokrewne|związki frazeologiczne)\s*:?\s*$",
        re.IGNORECASE,
    )

    for line in lines:
        line = line.strip()
        if not line:
            continue

        if defn_headers.match(line):
            in_definition_section = True
            continue

        if defn_text_markers.match(line):
            in_definition_section = True
            continue

        if end_markers.match(line):
            if in_definition_section:
                in_definition_section = False
            continue

        if re.match(r"^={2,4}\s*\S", line):
            if in_definition_section and not defn_headers.match(line):
                in_definition_section = False
            continue

        if not in_definition_section:
            continue

        if skip_line.match(line):
            continue

        if word and line.lower() == word.lower():
            continue
        if word and re.match(re.escape(word) + r"\s*\(", line, re.IGNORECASE):
            continue
        if word and re.match(re.escape(word) + r"\s+[mfnžcMFNŽC]\b", line, re.IGNORECASE):
            continue

        if re.match(r"^\S+\s*¦", line):
            continue
        if "·" in line or re.match(r".*Plural\s*:", line):
            continue
        if re.match(r"^\\", line):
            continue
        if re.match(r"^[a-záàâãéèêíóòôõúüçñ.·ˈˌ]+\s*\\", line, re.IGNORECASE):
            continue
        if re.match(r"^\w+\s*\(?\s*approfondimento", line, re.IGNORECASE):
            continue
        if re.match(r"^(de|het|een|die|das|der)\s+\w+\s+[vmfno]\b", line, re.IGNORECASE):
            continue
        if re.match(
            r"^[a-záàâãéèêíóòôõúüçñ.·ˈˌ]+,?\s*(masculino|feminino|comum|neutro|féminin|masculin|m\s|f\s|m sing|f sing)",
            line,
            re.IGNORECASE,
        ):
            continue
        if re.match(
            r"^\w+\s*\((plural|third-person|present|past|pl\.)\b",
            line,
            re.IGNORECASE,
        ):
            continue
        if re.match(r"^\w+\s+\(\d+", line):
            continue

        m = re.match(r"^\[(\d+)\]\s+(.+)", line)
        if m and len(m.group(2)) > 5:
            return m.group(2).strip()[:300]

        m = re.match(r"^\([\d.]+\)\s+(.+)", line)
        if m:
            defn = m.group(1).strip()
            if re.match(r"(zdrobn|zgrub|forma)\b", defn, re.IGNORECASE):
                continue
            if len(defn) > 5:
                return defn[:300]
            continue

        m = re.match(r"^\d+\.?\s+(.*)", line)
        if m and len(m.group(1)) > 3:
            text = m.group(1).strip()
            return text[:300]

        if line.startswith("▸") or line.startswith("►"):
            continue

        if len(line) > 3:
            return line[:300]

    return _fallback_extract_definition(extract, word=word)


# Language-specific lemma suffixes
LEMMA_SUFFIXES = {
    "tr": ["mek", "mak"],
    "az": ["mək", "maq"],
}

# Suffix stripping rules for inflected forms
LEMMA_STRIP_RULES = {
    "es": [("es", ""), ("as", "a"), ("os", "o"), ("s", "")],
    "pt": [("ões", "ão"), ("es", ""), ("as", "a"), ("os", "o"), ("s", "")],
    "fr": [("eaux", "eau"), ("aux", "al"), ("es", "e"), ("s", "")],
    "it": [
        ("chi", "co"),
        ("ghi", "go"),
        ("ni", "ne"),
        ("li", "le"),
        ("hi", "o"),
        ("i", "o"),
        ("e", "a"),
    ],
    "ca": [("ns", "n"), ("es", ""), ("s", "")],
    "ro": [("uri", ""), ("i", ""), ("e", "")],
    "de": [("ern", ""), ("en", ""), ("er", ""), ("e", "")],
    "nl": [("en", ""), ("er", ""), ("s", "")],
    "sv": [
        ("arna", ""),
        ("orna", ""),
        ("erna", ""),
        ("ar", ""),
        ("er", ""),
        ("or", ""),
        ("en", ""),
        ("et", ""),
        ("na", ""),
    ],
    "nb": [("ene", ""), ("er", ""), ("et", "")],
    "nn": [("ane", ""), ("ar", ""), ("et", "")],
    "hr": [("ovima", ""), ("evima", ""), ("ovi", ""), ("evi", ""), ("a", ""), ("i", ""), ("e", "")],
    "sr": [("ови", ""), ("еви", ""), ("а", ""), ("и", ""), ("е", "")],
    "bg": [("етата", "е"), ("ите", ""), ("ата", ""), ("ът", ""), ("та", ""), ("а", ""), ("и", "")],
    "ru": [("ов", ""), ("ей", ""), ("а", ""), ("ы", ""), ("и", "")],
    "uk": [("ів", ""), ("ей", ""), ("а", ""), ("и", ""), ("і", "")],
    "cs": [("ů", ""), ("ech", ""), ("y", ""), ("e", ""), ("i", "")],
    "sk": [("ov", ""), ("ách", ""), ("y", ""), ("e", ""), ("i", "")],
    "sl": [("ov", ""), ("ev", ""), ("i", ""), ("e", ""), ("a", "")],
    "fi": [
        ("ssa", ""),
        ("ssä", ""),
        ("sta", ""),
        ("stä", ""),
        ("lla", ""),
        ("llä", ""),
        ("lta", ""),
        ("ltä", ""),
        ("n", ""),
        ("t", ""),
    ],
    "et": [("de", ""), ("te", ""), ("d", "")],
    "hu": [("ban", ""), ("ben", ""), ("nak", ""), ("nek", ""), ("k", ""), ("t", "")],
}


def _build_candidates(word, lang_code):
    """Generate lookup candidates: original, title-case, lemma additions, lemma stripping."""
    candidates = [word]
    if word[0].islower():
        candidates.append(word[0].upper() + word[1:])
    for suffix in LEMMA_SUFFIXES.get(lang_code, []):
        candidates.append(word + suffix)
    for strip_suffix, replacement in LEMMA_STRIP_RULES.get(lang_code, []):
        if word.lower().endswith(strip_suffix) and len(word) > len(strip_suffix):
            base = word[: len(word) - len(strip_suffix)] + replacement
            if len(base) >= 2 and base not in candidates:
                candidates.append(base)
    return candidates


_GARBAGE_DEFINITION_RE = re.compile(
    r"^("
    r"uttal:|"
    r"IPA|발음|표기|"
    r"어원:|etymologi|Herkunft|"
    r"Ennek a szónak még nincs|"
    r"Définition manquante|"
    r"Δεν βρέθηκε ορισμός|"
    r"===|"
    r"\[\[|\{\{"
    r")",
    re.IGNORECASE,
)


def _is_garbage_definition(defn):
    """Return True if a parsed definition is clearly not a real definition."""
    if not defn or len(defn) < 3:
        return True
    return bool(_GARBAGE_DEFINITION_RE.search(defn))


def fetch_native_wiktionary(word, lang_code):
    """Try native-language Wiktionary via MediaWiki API. Returns dict or None."""
    wikt_lang = WIKT_LANG_MAP.get(lang_code, lang_code)
    candidates = _build_candidates(word, lang_code)

    for try_word in candidates:
        api_url = (
            f"https://{wikt_lang}.wiktionary.org/w/api.php?"
            f"action=query&titles={urllib.parse.quote(try_word)}"
            f"&prop=extracts&explaintext=1&format=json"
        )
        try:
            req = urlreq.Request(api_url, headers={"User-Agent": "WordleGlobal/1.0"})
            with urlreq.urlopen(req, timeout=5) as resp:
                data = json.loads(resp.read())
                pages = data.get("query", {}).get("pages", {})
                for pid, page in pages.items():
                    if pid == "-1":
                        continue
                    extract = page.get("extract", "").strip()
                    if not extract:
                        continue
                    defn = parse_wikt_definition(extract, word=try_word, lang_code=wikt_lang)
                    if defn and not _is_garbage_definition(defn):
                        return {
                            "definition": defn,
                            "source": "native",
                            "url": f"https://{wikt_lang}.wiktionary.org/wiki/{urllib.parse.quote(try_word)}",
                        }
        except Exception:
            pass
    return None


def fetch_english_definition(word, lang_code):
    """Fetch an English-language definition via English Wiktionary REST API."""
    try:
        url = f"https://en.wiktionary.org/api/rest_v1/page/definition/{urllib.parse.quote(word.lower())}"
        req = urlreq.Request(url, headers={"User-Agent": "WordleGlobal/1.0"})
        with urlreq.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read())
            for try_lang in [lang_code, "en"]:
                for entry in data.get(try_lang, []):
                    for defn in entry.get("definitions", []):
                        raw_def = defn.get("definition", "")
                        clean_def = strip_html(raw_def)
                        if clean_def:
                            return clean_def[:200]
    except Exception:
        pass
    return None


_FORM_OF_RE = re.compile(
    r"^(?:(?:feminine|masculine|neuter|singular|plural|diminutive|augmentative|"
    r"alternative|comparative|superlative|past|present|gerund|"
    r"(?:first|second|third)[- ]person|imperative|infinitive|"
    r"nominative|genitive|dative|accusative|ablative|instrumental)\s+)*"
    r"(?:form|plural|tense|participle|conjugation)?\s*"
    r"(?:of|de|di|du|von|van)\s+(\w+)",
    re.IGNORECASE,
)


def _follow_form_of(definition, lang_code):
    """If definition is 'X form of Y', look up Y and return its definition."""
    m = _FORM_OF_RE.match(definition)
    if m:
        base_word = m.group(1)
        defn = fetch_english_definition(base_word, lang_code)
        if defn:
            return defn
    return None
