#!/usr/bin/env python3
"""Discover and rank semantic axes automatically.

Given a seed candidate pool of ~80 anchor-pair dimensions, score each one on
four criteria (AUC coherence, variance captured, anchor strength, PCA
alignment), then greedily select a final set of ~25 with orthogonality
rejection.

All scoring is automatic: no LLM calls are needed beyond fetching embeddings
for any anchor words not already in our cached vocab. Test words for AUC are
generated by k-NN bootstrap (the 15 nearest neighbours of each anchor in the
existing vocab).

Usage:
    uv run python -m scripts.semantic.find_axes
    uv run python -m scripts.semantic.find_axes --target-count 30 --orth 0.55
    uv run python -m scripts.semantic.find_axes --dry-run

Outputs:
    scripts/semantic/axis_report.md   — full ranked report (every candidate)
    scripts/semantic/axis_selected.json — the accepted set, ready for promotion

Does NOT modify production data/semantic/axes.json. Inspect the report,
decide which axes to promote manually.
"""

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
from dotenv import load_dotenv
from openai import OpenAI
from sklearn.decomposition import PCA
from sklearn.metrics import roc_auc_score

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent.parent
EMBEDDINGS_FILE = REPO_ROOT / "data" / "semantic" / "embeddings.json"
REPORT_FILE = SCRIPT_DIR / "axis_report.md"
SELECTED_FILE = SCRIPT_DIR / "axis_selected.json"
LLM_CANDIDATES_CACHE = SCRIPT_DIR / "llm_candidates.json"

EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMS = 512
LLM_MODEL = "gpt-5.2"
LLM_CANDIDATE_COUNT = 120

# ~80 candidate axes covering physical, sensory, affective, temporal,
# evaluative, and social dimensions. Each is a (low_anchor, high_anchor) pair
# of single-token common English words. The greedy selector will prune
# redundant ones based on orthogonality to the embedding space.
CANDIDATE_AXES: dict[str, dict[str, str]] = {
    # --- Physical / spatial ---
    "size":         {"low": "tiny",       "high": "enormous"},
    "height":       {"low": "short",      "high": "tall"},
    "width":        {"low": "narrow",     "high": "wide"},
    "depth":        {"low": "shallow",    "high": "deep"},
    "weight":       {"low": "light",      "high": "heavy"},
    "density":      {"low": "sparse",     "high": "dense"},
    "distance":     {"low": "near",       "high": "far"},
    # --- Motion / dynamics ---
    "speed":        {"low": "slow",       "high": "fast"},
    "activity":     {"low": "still",      "high": "moving"},
    "frequency":    {"low": "rare",       "high": "common"},
    # --- Sensory ---
    "temperature":  {"low": "freezing",   "high": "burning"},
    "brightness":   {"low": "dark",       "high": "bright"},
    "loudness":     {"low": "silent",     "high": "loud"},
    "hardness":     {"low": "soft",       "high": "hard"},
    "sharpness":    {"low": "dull",       "high": "sharp"},
    "wetness":      {"low": "dry",        "high": "wet"},
    "texture":      {"low": "smooth",     "high": "rough"},
    "taste":        {"low": "bitter",     "high": "sweet"},
    "spiciness":    {"low": "mild",       "high": "spicy"},
    "smelliness":   {"low": "odorless",   "high": "pungent"},
    "cleanliness":  {"low": "dirty",      "high": "clean"},
    "colorfulness": {"low": "gray",       "high": "colorful"},
    "transparency": {"low": "opaque",     "high": "transparent"},
    "flexibility":  {"low": "rigid",      "high": "flexible"},
    "fragility":    {"low": "sturdy",     "high": "fragile"},
    # --- Origin / construction ---
    "natural":      {"low": "artificial", "high": "natural"},
    "organic":      {"low": "synthetic",  "high": "organic"},
    "alive":        {"low": "inanimate",  "high": "alive"},
    "concreteness": {"low": "abstract",   "high": "concrete"},
    "handmade":     {"low": "manufactured","high": "handmade"},
    # --- Temporal ---
    "age":          {"low": "ancient",    "high": "modern"},
    "recency":      {"low": "old",        "high": "new"},
    "permanence":   {"low": "temporary",  "high": "permanent"},
    "era_past":     {"low": "future",     "high": "past"},
    # --- Affective / evaluative ---
    "emotion":      {"low": "sad",        "high": "joyful"},
    "morality":     {"low": "evil",       "high": "good"},
    "beauty":       {"low": "ugly",       "high": "beautiful"},
    "value":        {"low": "cheap",      "high": "precious"},
    "usefulness":   {"low": "useless",    "high": "useful"},
    "danger":       {"low": "safe",       "high": "dangerous"},
    "fear":         {"low": "comforting", "high": "scary"},
    "calm":         {"low": "chaotic",    "high": "calm"},
    "formality":    {"low": "casual",     "high": "formal"},
    "seriousness":  {"low": "playful",    "high": "serious"},
    # --- Cognitive ---
    "complexity":   {"low": "simple",     "high": "complex"},
    "familiarity":  {"low": "unfamiliar", "high": "familiar"},
    "clarity":      {"low": "vague",      "high": "clear"},
    "mystery":      {"low": "obvious",    "high": "mysterious"},
    "intelligence": {"low": "dumb",       "high": "brilliant"},
    # --- Social ---
    "social":       {"low": "solitary",   "high": "social"},
    "public":       {"low": "private",    "high": "public"},
    "friendliness": {"low": "hostile",    "high": "friendly"},
    "popularity":   {"low": "obscure",    "high": "popular"},
    "power":        {"low": "weak",       "high": "powerful"},
    "freedom":      {"low": "bound",      "high": "free"},
    "wealth":       {"low": "poor",       "high": "rich"},
    # --- Context / setting ---
    "indoor":       {"low": "outdoor",    "high": "indoor"},
    "urban":        {"low": "rural",      "high": "urban"},
    "wild":         {"low": "tame",       "high": "wild"},
    "domestic":     {"low": "foreign",    "high": "domestic"},
    # --- Body / action ---
    "edible":       {"low": "inedible",   "high": "edible"},
    "portable":     {"low": "immovable",  "high": "portable"},
    "visible":      {"low": "hidden",     "high": "visible"},
    # --- Scale / abstract ---
    "order":        {"low": "chaotic",    "high": "ordered"},
    "purity":       {"low": "mixed",      "high": "pure"},
    "symmetry":     {"low": "asymmetric", "high": "symmetric"},
    "solidness":    {"low": "liquid",     "high": "solid"},
    "fullness":     {"low": "empty",      "high": "full"},
}


def generate_candidates_llm(
    client: OpenAI,
    n: int,
    cache_file: Path,
    regenerate: bool = False,
) -> dict[str, dict[str, str]]:
    """Ask an LLM to generate ~n bipolar semantic dimensions with single-word
    anchors. Cached to disk on first run; subsequent runs read the cache
    unless `regenerate=True` is passed.
    """
    if cache_file.exists() and not regenerate:
        print(f"Loading cached LLM candidates from {cache_file.name}...")
        with open(cache_file, encoding="utf-8") as f:
            cached = json.load(f)
        return cached.get("axes", {})

    print(f"Generating {n} candidate axes via LLM ({LLM_MODEL})...")
    user_prompt = (
        f"Generate {n} bipolar semantic dimensions for a word-guessing game.\n\n"
        "Each dimension is a pair of single-word English antonyms that spans a "
        "continuum of meaning. The pair must cleanly define a semantic direction "
        "in word embedding space, such that projecting any common noun onto it "
        "produces an interpretable score from low to high.\n\n"
        "## HARD REQUIREMENTS\n"
        "- Anchors MUST be single-token common English words (no compounds, no hyphens)\n"
        "- The NAME of the dimension must also be simple: either a single word or "
        "snake_case with at most 2 words. Avoid technical compounds like "
        "'color_temperature' or 'moisture_absorption' — pick a simpler name.\n"
        "- Both anchors must be concrete, unambiguous words\n"
        "- Each dimension must have a distinct name\n\n"
        "## POLYSEMY IS THE #1 FAILURE — AVOID IT AGGRESSIVELY\n"
        "An anchor word is polysemous if it has multiple common meanings. Polysemous "
        "anchors pull the wrong sense and ruin the axis. Examples of words to REFUSE:\n\n"
        "- 'cool' (means both 'cold' AND 'awesome' AND 'calm')\n"
        "- 'warm' (means both 'hot' AND 'friendly' AND 'cozy')\n"
        "- 'free' (means both 'no cost' AND 'liberated' AND 'unoccupied')\n"
        "- 'light' (means both 'not heavy' AND 'bright' AND 'pale')\n"
        "- 'hot' (means both 'high temperature' AND 'attractive' AND 'popular')\n"
        "- 'sharp' (means both 'pointed' AND 'clever' AND 'severe')\n"
        "- 'hard' (means both 'firm' AND 'difficult')\n"
        "- 'flat' (means both 'level' AND 'boring' AND 'apartment')\n"
        "- 'stingy' (neighbors include 'tight, painful, burning' — wrong sense)\n"
        "- 'repellent' (means both 'water-repelling' AND 'disgusting')\n"
        "- 'lopsided' (too rare, neighbors are just 'unbalanced state' metaphors)\n\n"
        "PREFER unambiguous synonyms. Instead of 'cool/warm' for temperature, use "
        "'freezing/burning'. Instead of 'repellent/absorbent', pick one of: "
        "'waterproof/soaked', 'arid/drenched'. Instead of 'stingy/generous', use "
        "'miserly/lavish'. Instead of 'flat/curved', use 'planar/round' — or just "
        "don't include the dimension if you can't find a clean anchor.\n\n"
        "## WHAT COUNTS AS A GOOD DIMENSION\n"
        "- Covers a real axis in how we categorize things: physical properties "
        "(size, weight, speed), sensory qualities (temperature, loudness, brightness), "
        "evaluative judgments (danger, value, morality), temporal relations "
        "(ancient/modern), social qualities (formal/casual), functional properties "
        "(useful/useless), emotional tone (sad/joyful), abstractness, concreteness, etc.\n"
        "- Diverse from other dimensions — 'alive' and 'natural' overlap, don't repeat\n"
        "- Applicable to common nouns (not just obscure technical terms)\n\n"
        'Return JSON: {"dimensions": [{"name": "size", "low": "tiny", "high": '
        '"enormous"}, ...]}\n\n'
        f"Return exactly {n} dimensions. If you cannot find {n} without polysemy "
        "violations, return fewer — quality over count."
    )
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {
                "role": "system",
                "content": "You are a computational linguist designing semantic axes for a word game. Return valid JSON only.",
            },
            {"role": "user", "content": user_prompt},
        ],
        # gpt-5.x reserves a big chunk of the token budget for internal reasoning
        # before emitting output. 8000 was enough for ~120 dims; 300 dims of
        # verbose JSON plus reasoning needs a much larger budget.
        max_completion_tokens=32000,
        response_format={"type": "json_object"},
    )
    content = (response.choices[0].message.content or "").strip()
    if not content:
        finish = response.choices[0].finish_reason
        usage = response.usage
        raise RuntimeError(
            f"LLM returned empty content (finish_reason={finish}, usage={usage}). "
            "Likely hit max_completion_tokens with reasoning-heavy model — bump the budget."
        )
    data = json.loads(content)
    dims = data.get("dimensions", [])
    axes: dict[str, dict[str, str]] = {}
    for d in dims:
        name = d.get("name", "").lower().strip()
        low = d.get("low", "").lower().strip()
        high = d.get("high", "").lower().strip()
        if not name or not low or not high:
            continue
        # Skip multi-word anchors
        if " " in low or " " in high or "-" in low or "-" in high:
            continue
        if not low.isalpha() or not high.isalpha():
            continue
        if name in axes:
            continue
        axes[name] = {"low": low, "high": high}
    print(f"  LLM returned {len(dims)} dimensions, {len(axes)} passed filters")

    with open(cache_file, "w") as f:
        json.dump({"axes": axes, "model": LLM_MODEL, "count": len(axes)}, f, indent=2)
    return axes


def validate_axes_llm(
    client: OpenAI,
    candidates: list[str],
    scored: dict[str, dict],
    merged: dict[str, dict[str, str]],
) -> dict[str, dict]:
    """LLM-as-judge pass: for each axis, show its bootstrapped test words and
    ask whether the words actually represent the claimed concept.

    Catches polysemy (the one failure mode that AUC, variance, and orthogonality
    can't detect, because held-out neighbors come from the same polysemous
    neighborhood as the anchors).

    Returns a dict mapping axis name → {rating, actual_concept, verdict}.
    One API call for the whole batch (~$0.001).
    """
    print(f"\nLLM-as-judge validation of {len(candidates)} candidates...")
    items = []
    for name in candidates:
        pair = merged[name]
        m = scored[name]
        items.append(
            {
                "name": name,
                "intended": f"{pair['low']} ↔ {pair['high']}",
                "low_words": m["test_low"][:10],
                "high_words": m["test_high"][:10],
            }
        )

    user_prompt = (
        "You are validating semantic axes for a word-guessing game. Each axis "
        "claims to measure a specific concept. Bootstrapped test words are drawn "
        "from the embedding space near each anchor. Your job: rate how well the "
        "test words actually represent the claimed concept.\n\n"
        "Common failure: POLYSEMY. An anchor with multiple meanings pulls the "
        "wrong sense from the embedding. For example if the anchor 'cool' is "
        "meant to anchor 'cold', but the low test words are ['steady, amazing, "
        "classic, charged'], the anchor actually pulled the 'cool = awesome' "
        "sense. Give that a low rating.\n\n"
        "For each axis, return:\n"
        "  - rating: 0-10 (10 = test words perfectly capture the concept; "
        "    0 = test words are unrelated or pulled the wrong sense)\n"
        "  - actual_concept: a 1-sentence description of what the test words "
        "    actually seem to represent (may differ from intended)\n"
        "  - verdict: 'keep' if rating >= 6, 'drop' if below\n\n"
        "Return JSON: {\"axes\": {\"size\": {\"rating\": 9, \"actual_concept\": "
        "\"physical magnitude\", \"verdict\": \"keep\"}, ...}}\n\n"
        f"Axes to validate:\n{json.dumps(items, indent=2)}"
    )
    response = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {
                "role": "system",
                "content": "You are a computational linguist auditing word-embedding axes. Return valid JSON only.",
            },
            {"role": "user", "content": user_prompt},
        ],
        max_completion_tokens=8000,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content.strip()
    data = json.loads(content)
    verdicts = data.get("axes", {})
    # Normalize keys (strip any extra text the model might add)
    return {k.lower().strip(): v for k, v in verdicts.items()}


def merge_candidates(
    hand: dict[str, dict[str, str]],
    llm: dict[str, dict[str, str]],
) -> tuple[dict[str, dict[str, str]], dict[str, str]]:
    """Merge two candidate sources. Returns (merged, source_map) where
    source_map tracks which source each axis came from ('hand', 'llm', 'both')."""
    merged: dict[str, dict[str, str]] = {}
    source: dict[str, str] = {}
    for name, pair in hand.items():
        merged[name] = pair
        source[name] = "hand"
    for name, pair in llm.items():
        if name in merged:
            # Conflict: keep hand version but tag as "both"
            source[name] = "both"
        else:
            merged[name] = pair
            source[name] = "llm"
    return merged, source


def load_existing_embeddings() -> tuple[dict[str, np.ndarray], list[str], np.ndarray]:
    """Load the cached PoC embeddings. Returns (word→vec dict, words list, matrix)."""
    with open(EMBEDDINGS_FILE, encoding="utf-8") as f:
        data = json.load(f)
    words = data["words"]
    matrix = np.asarray(data["vectors"], dtype=np.float32)
    word_to_vec = {w: matrix[i] for i, w in enumerate(words)}
    return word_to_vec, words, matrix


def fetch_missing_embeddings(
    client: OpenAI, needed: list[str], existing: dict[str, np.ndarray]
) -> dict[str, np.ndarray]:
    """Fetch embeddings for any anchor words not already in the cache."""
    missing = [w for w in needed if w not in existing]
    if not missing:
        return existing
    print(f"Fetching {len(missing)} missing anchor embeddings...")
    for i in range(0, len(missing), 200):
        batch = missing[i : i + 200]
        for attempt in range(3):
            try:
                resp = client.embeddings.create(
                    model=EMBEDDING_MODEL, input=batch, dimensions=EMBEDDING_DIMS
                )
                break
            except Exception as e:
                if attempt == 2:
                    raise
                print(f"  retry {attempt + 1}: {e}", file=sys.stderr)
                time.sleep(2 * (attempt + 1))
        for j, item in enumerate(sorted(resp.data, key=lambda d: d.index)):
            vec = np.asarray(item.embedding, dtype=np.float32)
            norm = float(np.linalg.norm(vec))
            if norm > 0:
                vec /= norm
            existing[batch[j]] = vec
    return existing


def knn_bootstrap(
    anchor_vec: np.ndarray,
    vocab_words: list[str],
    vocab_matrix: np.ndarray,
    k: int,
    exclude: set[str],
    skip_top: int = 30,
) -> list[str]:
    """Return vocab words ranked between `skip_top` and `skip_top + k` closest.

    Skipping the very-top matches avoids the "memorization" effect where the
    anchor's closest neighbours are near-synonyms that trivially project onto
    the anchor direction. The held-out middle band is a stronger test of
    whether the axis captures the concept beyond its anchors.
    """
    sims = vocab_matrix @ anchor_vec
    order = np.argsort(-sims)
    out: list[str] = []
    rank = 0
    for idx in order:
        w = vocab_words[idx]
        if w in exclude:
            continue
        rank += 1
        if rank <= skip_top:
            continue
        out.append(w)
        if len(out) >= k:
            break
    return out


def score_axis(
    anchor_low: str,
    anchor_high: str,
    word_to_vec: dict[str, np.ndarray],
    vocab_words: list[str],
    vocab_matrix: np.ndarray,
    pca_components: np.ndarray,
    k_bootstrap: int = 15,
) -> dict[str, float] | None:
    """Score a candidate axis. Returns None if anchors are missing."""
    if anchor_low not in word_to_vec or anchor_high not in word_to_vec:
        return None

    v_low = word_to_vec[anchor_low]
    v_high = word_to_vec[anchor_high]
    raw_direction = v_high - v_low
    anchor_strength = float(np.linalg.norm(raw_direction))
    if anchor_strength < 1e-9:
        return None
    axis_vec = raw_direction / anchor_strength

    # Bootstrap test words via k-NN
    exclude = {anchor_low, anchor_high}
    test_low = knn_bootstrap(v_low, vocab_words, vocab_matrix, k_bootstrap, exclude)
    test_high = knn_bootstrap(v_high, vocab_words, vocab_matrix, k_bootstrap, exclude)

    # AUC: project test words onto axis, measure separation
    low_proj = np.array([float(word_to_vec[w] @ axis_vec) for w in test_low])
    high_proj = np.array([float(word_to_vec[w] @ axis_vec) for w in test_high])
    y_true = np.concatenate([np.zeros(len(low_proj)), np.ones(len(high_proj))])
    y_score = np.concatenate([low_proj, high_proj])
    try:
        auc = float(roc_auc_score(y_true, y_score))
    except ValueError:
        auc = 0.5

    # Variance captured: std of projections over full vocab
    variance = float(np.std(vocab_matrix @ axis_vec))

    # PCA alignment: max absolute cosine with any of the top 50 PCs
    pc_alignments = np.abs(pca_components @ axis_vec)
    pca_align = float(np.max(pc_alignments))

    return {
        "auc": auc,
        "variance": variance,
        "anchor_strength": anchor_strength,
        "pca_align": pca_align,
        "axis_vec": axis_vec,  # kept for orthogonality checks, stripped from report
        "test_low": test_low,
        "test_high": test_high,
    }


def composite_score(metrics: dict) -> float:
    """Weighted composite.

    AUC is a hard gate (we drop candidates below the threshold), not a ranker
    — near-ceiling scores don't discriminate well. Ranking is done by:
      - variance captured (rank-normalized) — does the axis spread the vocab?
      - PCA alignment — does the direction have real variance behind it?
      - AUC margin above the threshold — residual signal for ties
    """
    auc_margin = max(0.0, metrics["auc"] - 0.75) / 0.25  # → [0, 1]
    return 0.45 * metrics["variance_rank"] + 0.35 * metrics["pca_align"] + 0.20 * auc_margin


def rank_normalize(values: list[float]) -> list[float]:
    """Map values to their rank in [0, 1], with smallest → 0 and largest → 1."""
    n = len(values)
    order = sorted(range(n), key=lambda i: values[i])
    ranks = [0.0] * n
    for r, i in enumerate(order):
        ranks[i] = r / max(n - 1, 1)
    return ranks


def _build_cos_matrix(names: list[str], scored: dict[str, dict]) -> tuple[np.ndarray, dict[str, int]]:
    """Stack all axis vectors into a matrix and return |V V^T| + name→row index.

    Used by the orthogonal-subset selector so per-trial pairwise cosine lookups
    are O(k²) numpy ops instead of O(k²) dict lookups + dot products.
    """
    V = np.stack([scored[n]["axis_vec"] for n in names]).astype(np.float32)
    C = np.abs(V @ V.T)
    np.fill_diagonal(C, 0.0)  # self-cosines don't count
    idx = {n: i for i, n in enumerate(names)}
    return C, idx


def max_pairwise_cos_idx(idxs: np.ndarray, C: np.ndarray) -> float:
    """Max |cos| among a subset, given precomputed full cosine matrix."""
    if len(idxs) < 2:
        return 0.0
    sub = C[np.ix_(idxs, idxs)]
    return float(sub.max())


def mean_pairwise_cos_idx(idxs: np.ndarray, C: np.ndarray) -> float:
    """Mean |cos| among a subset, using precomputed matrix."""
    k = len(idxs)
    if k < 2:
        return 0.0
    sub = C[np.ix_(idxs, idxs)]
    # diagonal is zero, so sum of sub = 2 × (sum over unique pairs)
    return float(sub.sum()) / (k * (k - 1))


def max_pairwise_cos(names: list[str], scored: dict[str, dict]) -> float:
    """Back-compat wrapper — builds the matrix each call. Only used for final reporting."""
    if len(names) < 2:
        return 0.0
    C, _ = _build_cos_matrix(names, scored)
    return float(C.max())


def mean_pairwise_cos(names: list[str], scored: dict[str, dict]) -> float:
    """Back-compat wrapper — builds the matrix each call. Only used for final reporting."""
    k = len(names)
    if k < 2:
        return 0.0
    C, _ = _build_cos_matrix(names, scored)
    return float(C.sum()) / (k * (k - 1))


def max_orthogonal_subset(
    candidates: list[str],
    scored: dict[str, dict],
    k: int,
    composite_weight: float = 0.15,
    refinement_iters: int = 200,
) -> list[str]:
    """Select k candidates that approximately maximize mutual orthogonality.

    Two phases:
      1. Farthest-first traversal seeded by the highest-composite candidate.
         At each step, add the candidate whose max |cos| to the already-selected
         set is smallest. Composite score acts as a weak tie-breaker so that
         among equally orthogonal choices we prefer informative ones.
      2. Local search refinement: repeatedly try to swap one selected axis with
         one non-selected axis; accept if it reduces the max pairwise |cos|.
         Converges in tens of iterations at this scale.

    This is an approximation of the NP-hard max-dispersion problem. Precomputes
    the full |V V^T| cosine matrix once so per-trial lookups are O(k²) numpy
    slices, not O(k²) dict+dot product calls. At n=600, k=120 this runs in
    seconds instead of hours.
    """
    if not candidates:
        return []

    # Precompute full cosine matrix across ALL candidates once
    C, idx = _build_cos_matrix(candidates, scored)
    n = len(candidates)
    composite_arr = np.array([scored[c]["composite"] for c in candidates], dtype=np.float32)

    # Phase 1: farthest-first traversal (vectorized)
    # Start with the highest-composite candidate
    selected_rows: list[int] = [int(np.argmax(composite_arr))]
    selected_mask = np.zeros(n, dtype=bool)
    selected_mask[selected_rows[0]] = True

    while len(selected_rows) < k and len(selected_rows) < n:
        # max |cos| of each non-selected candidate to the selected set
        sel_cos = C[:, selected_rows].max(axis=1)  # shape (n,)
        # weak composite tiebreaker
        adjusted = sel_cos - composite_weight * composite_arr
        adjusted[selected_mask] = np.inf
        best = int(np.argmin(adjusted))
        selected_rows.append(best)
        selected_mask[best] = True

    # Phase 2: 1-swap local search, vectorized
    selected_arr = np.array(selected_rows, dtype=np.int64)
    for _iter in range(refinement_iters):
        sub = C[np.ix_(selected_arr, selected_arr)]
        current_max = float(sub.max())
        improved = False
        # For each position i in selected, try swapping with every non-selected candidate
        for i in range(len(selected_arr)):
            held = np.delete(selected_arr, i)
            held_mask = np.zeros(n, dtype=bool)
            held_mask[held] = True
            # For each candidate c (not in held), new_max = max(
            #   pairwise max among held (constant),
            #   max C[c, held]
            # )
            held_sub = C[np.ix_(held, held)]
            held_max = float(held_sub.max()) if len(held) > 1 else 0.0
            # candidate ↔ held max cosine, per candidate
            cand_to_held = C[:, held].max(axis=1)
            new_max = np.maximum(held_max, cand_to_held)
            # Block held positions (can't swap in something already selected)
            new_max[held_mask] = np.inf
            new_max[selected_arr[i]] = np.inf  # can't "swap" with self
            best_cand = int(np.argmin(new_max))
            if new_max[best_cand] < current_max - 1e-6:
                selected_arr = np.concatenate([held, [best_cand]])
                current_max = float(new_max[best_cand])
                improved = True
                break
        if not improved:
            break

    return [candidates[int(i)] for i in selected_arr]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target-count", type=int, default=25, help="How many axes to accept")
    parser.add_argument("--min-auc", type=float, default=0.75, help="Drop candidates below this AUC")
    parser.add_argument("--source", choices=["both", "llm", "hand"], default="both",
                        help="Candidate source: hand-coded, LLM-generated, or merged")
    parser.add_argument("--regenerate-llm", action="store_true",
                        help="Re-query the LLM for candidates (ignores cache)")
    parser.add_argument("--llm-count", type=int, default=LLM_CANDIDATE_COUNT,
                        help="How many candidates to request from the LLM")
    parser.add_argument("--skip-validation", action="store_true",
                        help="Skip the LLM-as-judge polysemy validation pass")
    parser.add_argument("--dry-run", action="store_true", help="Skip OpenAI fetch, use cache only")
    args = parser.parse_args()

    load_dotenv(REPO_ROOT / ".env")

    print("Loading cached embeddings...")
    word_to_vec, vocab_words, vocab_matrix = load_existing_embeddings()
    print(f"  {len(vocab_words)} words, {vocab_matrix.shape[1]} dims")

    # Assemble candidate pool
    import os
    api_key = os.environ.get("OPENAI_API_KEY")
    client: OpenAI | None = None
    if api_key and not args.dry_run:
        client = OpenAI(api_key=api_key)

    llm_axes: dict[str, dict[str, str]] = {}
    if args.source in ("llm", "both"):
        if client is None:
            print("WARNING: no OPENAI_API_KEY — LLM candidates skipped")
        else:
            llm_axes = generate_candidates_llm(
                client, args.llm_count, LLM_CANDIDATES_CACHE, regenerate=args.regenerate_llm
            )
    hand_axes = CANDIDATE_AXES if args.source in ("hand", "both") else {}

    merged, source_map = merge_candidates(hand_axes, llm_axes)
    print(f"Candidate pool: {len(merged)} ({len(hand_axes)} hand, {len(llm_axes)} llm)")

    # Collect every anchor word we'll need
    all_anchors: list[str] = []
    for pair in merged.values():
        all_anchors.append(pair["low"])
        all_anchors.append(pair["high"])
    all_anchors = sorted(set(all_anchors))
    missing = [w for w in all_anchors if w not in word_to_vec]
    print(f"  anchors needed: {len(all_anchors)}, missing: {len(missing)}")

    if missing and not args.dry_run:
        if client is None:
            print("ERROR: OPENAI_API_KEY not set", file=sys.stderr)
            return 1
        word_to_vec = fetch_missing_embeddings(client, all_anchors, word_to_vec)
    elif missing and args.dry_run:
        print("  (skipping fetch; candidates with missing anchors will be dropped)")

    print("Running PCA on vocab matrix (top 50 components)...")
    n_components = min(50, vocab_matrix.shape[0], vocab_matrix.shape[1])
    pca = PCA(n_components=n_components)
    pca.fit(vocab_matrix)
    print(f"  top-{n_components} components explain {pca.explained_variance_ratio_.sum():.1%} of variance")

    print(f"\nScoring {len(merged)} candidates...")
    scored: dict[str, dict] = {}
    for name, pair in merged.items():
        metrics = score_axis(
            pair["low"],
            pair["high"],
            word_to_vec,
            vocab_words,
            vocab_matrix,
            pca.components_,
        )
        if metrics is None:
            continue
        scored[name] = metrics

    if not scored:
        print("No candidates scored. Exiting.", file=sys.stderr)
        return 1

    # Rank-normalize variance for the composite
    names = list(scored.keys())
    variance_ranks = rank_normalize([scored[n]["variance"] for n in names])
    for n, vr in zip(names, variance_ranks):
        scored[n]["variance_rank"] = vr
        scored[n]["composite"] = composite_score(scored[n])

    # Filter by min AUC
    eligible = [n for n in scored if scored[n]["auc"] >= args.min_auc]
    print(f"  {len(eligible)} pass min_auc >= {args.min_auc}")

    print(f"\nMax-orthogonal subset selection (k={args.target_count})...")
    accepted = max_orthogonal_subset(eligible, scored, args.target_count)
    max_cos = max_pairwise_cos(accepted, scored)
    mean_cos = mean_pairwise_cos(accepted, scored)
    print(f"  accepted (phase 1): {len(accepted)}")
    print(f"  max pairwise |cos| in accepted set: {max_cos:.3f}")
    print(f"  mean pairwise |cos| in accepted set: {mean_cos:.3f}")

    # LLM-as-judge validation pass — catches polysemy that AUC can't.
    # Loops: select → validate → drop bad → re-select from remaining → validate
    # only the newly added → repeat until no drops in a full pass or we can't
    # fill the target count.
    validation: dict[str, dict] = {}
    dropped_polysemous: list[str] = []
    if client is not None and not args.skip_validation:
        eligible_survivors = list(eligible)
        max_loops = 8
        loop = 0
        while loop < max_loops:
            loop += 1
            to_validate = [n for n in accepted if n not in validation]
            if not to_validate:
                break
            print(f"\nLoop {loop}: validating {len(to_validate)} new axes...")
            fresh = validate_axes_llm(client, to_validate, scored, merged)
            validation.update(fresh)
            loop_drops = [
                n for n in to_validate
                if validation.get(n, {}).get("verdict") == "drop"
            ]
            for name in loop_drops:
                v = validation[name]
                print(f"  ✗ {name}: rating {v.get('rating', '?')} — {v.get('actual_concept', '?')[:80]}")
            if not loop_drops:
                print(f"  all {len(to_validate)} accepted — validation stable")
                break
            dropped_polysemous.extend(loop_drops)
            eligible_survivors = [n for n in eligible_survivors if n not in loop_drops]
            if len(eligible_survivors) < args.target_count:
                print(f"  only {len(eligible_survivors)} survivors left — stopping")
                break
            print(f"  re-selecting from {len(eligible_survivors)} survivors...")
            accepted = max_orthogonal_subset(eligible_survivors, scored, args.target_count)
        max_cos = max_pairwise_cos(accepted, scored)
        mean_cos = mean_pairwise_cos(accepted, scored)
        final_kept = [n for n in accepted if validation.get(n, {}).get("verdict") == "keep"]
        print(f"\nFinal accepted: {len(final_kept)} validated / {len(accepted)} selected")
        print(f"  max pairwise |cos|: {max_cos:.3f}")
        print(f"  mean pairwise |cos|: {mean_cos:.3f}")
        print(f"  total dropped by validation: {len(dropped_polysemous)}")
        # Shrink accepted to only validated-keep axes (otherwise the final report
        # contains axes that were never judged)
        accepted = [n for n in accepted if validation.get(n, {}).get("verdict") == "keep"]

    rejected_redundant = [
        n for n in eligible if n not in accepted and n not in dropped_polysemous
    ]

    # --- Write report ---
    # Build a status map so every candidate shows in the main table
    accepted_set = set(accepted)
    redundant_set = set(rejected_redundant)
    status: dict[str, tuple[str, str]] = {}  # name → (label, detail)
    for name in accepted:
        status[name] = ("accepted", f"rank {accepted.index(name) + 1}")
    for name in rejected_redundant:
        m = scored[name]
        best_match = max(
            accepted,
            key=lambda a: abs(float(m["axis_vec"] @ scored[a]["axis_vec"])),
        )
        best_cos = abs(float(m["axis_vec"] @ scored[best_match]["axis_vec"]))
        status[name] = ("redundant", f"{best_match} ({best_cos:.2f})")
    for name, m in scored.items():
        if name in status:
            continue
        if m["auc"] < args.min_auc:
            status[name] = ("low_auc", f"{m['auc']:.2f}")
        else:
            status[name] = ("overflow", "past target count")

    # Build status for every candidate (for the full-table view)
    status: dict[str, tuple[str, str]] = {}
    for name in accepted:
        status[name] = ("accepted", f"rank {accepted.index(name) + 1}")
    for name in rejected_redundant:
        m = scored[name]
        best_match = max(
            accepted,
            key=lambda a: abs(float(m["axis_vec"] @ scored[a]["axis_vec"])),
        )
        best_cos = abs(float(m["axis_vec"] @ scored[best_match]["axis_vec"]))
        status[name] = ("overflow", f"closest: {best_match} ({best_cos:.2f})")
    for name, m in scored.items():
        if name in status:
            continue
        status[name] = ("low_auc", f"AUC {m['auc']:.2f}")

    print(f"\nWriting {REPORT_FILE}...")
    with open(REPORT_FILE, "w") as f:
        f.write("# Semantic Explorer — Axis Discovery Report\n\n")
        f.write(
            f"{len(scored)} candidates scored ({sum(1 for n in scored if source_map.get(n) == 'hand')} hand, "
            f"{sum(1 for n in scored if source_map.get(n) == 'llm')} llm, "
            f"{sum(1 for n in scored if source_map.get(n) == 'both')} both). "
            f"Composite = 0.45·variance_rank + 0.35·pca_alignment + 0.20·auc_margin. "
            f"AUC gate at {args.min_auc}. Selection: farthest-first + 1-swap local search "
            f"to jointly max orthogonality across {args.target_count} axes.\n\n"
        )
        f.write(
            f"**Accepted: {len(accepted)}** · "
            f"**Eligible but not selected: {len(rejected_redundant)}** · "
            f"**Low AUC: {sum(1 for s in status.values() if s[0] == 'low_auc')}**\n\n"
        )
        f.write(f"**Max pairwise |cos|: {max_cos:.3f}** (lower = more orthogonal)  \n")
        f.write(f"**Mean pairwise |cos|: {mean_cos:.3f}**\n\n")

        # --- Full candidate table, ranked by composite ---
        f.write("## All candidates (ranked by composite)\n\n")
        f.write("Status: ✓ accepted · · eligible but not picked · ✗ dropped (below AUC gate)\n\n")
        f.write("| Rank | St | Src | Axis | Anchors | AUC | Var | PCA | Comp | Status detail |\n")
        f.write("|------|----|-----|------|---------|-----|-----|-----|------|----------------|\n")
        all_sorted = sorted(scored.items(), key=lambda x: -x[1]["composite"])
        for rank, (name, m) in enumerate(all_sorted, 1):
            st, detail = status[name]
            icon = {"accepted": "✓", "overflow": "·", "low_auc": "✗"}[st]
            pair = merged[name]
            src = source_map.get(name, "?")[0].upper()  # H / L / B
            name_cell = f"**{name}**" if st == "accepted" else name
            f.write(
                f"| {rank} | {icon} | {src} | {name_cell} | {pair['low']} ↔ {pair['high']} "
                f"| {m['auc']:.3f} | {m['variance']:.3f} | {m['pca_align']:.3f} "
                f"| {m['composite']:.3f} | {detail} |\n"
            )

        # --- Accepted axes with their bootstrap test words ---
        f.write("\n## Accepted axes — bootstrapped test words\n\n")
        f.write(
            "Test words are vocab words ranked positions 30-45 closest to each anchor "
            "(k-NN bootstrap with held-out top-30). Sanity check for anchor polysemy.\n\n"
        )
        f.write("| Axis | Anchors | Test low | Test high |\n")
        f.write("|------|---------|----------|-----------|\n")
        for name in accepted:
            m = scored[name]
            pair = merged[name]
            low_sample = ", ".join(m["test_low"][:8])
            high_sample = ", ".join(m["test_high"][:8])
            f.write(
                f"| **{name}** | {pair['low']} ↔ {pair['high']} "
                f"| {low_sample} | {high_sample} |\n"
            )

        # --- Full orthogonality matrix across ALL scored candidates ---
        f.write("\n## Pairwise orthogonality (all candidates)\n\n")
        f.write(
            "Absolute cosine similarity between every pair of candidate axis vectors. "
            "Values `> 0.4` indicate redundancy; `> 0.6` is strong overlap. "
            "Sorted to put accepted axes first.\n\n"
        )
        # Build a pruned view: only show cells where at least one entry is > 0.3
        # to keep the matrix readable. Full data is in the JSON output.
        f.write("Showing only pairs with cosine ≥ 0.30 (full data in JSON).\n\n")
        f.write("| Axis A | Axis B | |cos| |\n|--------|--------|--------|\n")
        high_pairs: list[tuple[str, str, float]] = []
        names_list = list(scored.keys())
        for i in range(len(names_list)):
            for j in range(i + 1, len(names_list)):
                a, b = names_list[i], names_list[j]
                cos = abs(float(scored[a]["axis_vec"] @ scored[b]["axis_vec"]))
                if cos >= 0.30:
                    high_pairs.append((a, b, cos))
        high_pairs.sort(key=lambda x: -x[2])
        for a, b, cos in high_pairs[:40]:
            f.write(f"| {a} | {b} | {cos:.3f} |\n")
        if len(high_pairs) > 40:
            f.write(f"\n*(+{len(high_pairs) - 40} more pairs omitted)*\n")

    print(f"Writing {SELECTED_FILE}...")
    with open(SELECTED_FILE, "w") as f:
        out = {
            "version": 2,
            "target_count": args.target_count,
            "max_pairwise_cos": max_cos,
            "mean_pairwise_cos": mean_cos,
            "accepted": [
                {
                    "name": name,
                    "low": merged[name]["low"],
                    "high": merged[name]["high"],
                    "source": source_map.get(name, "?"),
                    "auc": scored[name]["auc"],
                    "variance": scored[name]["variance"],
                    "pca_align": scored[name]["pca_align"],
                    "composite": scored[name]["composite"],
                }
                for name in accepted
            ],
        }
        json.dump(out, f, indent=2)

    print(f"\nDone. Inspect {REPORT_FILE} for the full picture.")
    print(f"Accepted: {', '.join(accepted)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
