#!/usr/bin/env python3
"""Translate the 8 homepage UI keys for all languages missing translations."""

import json
import os

SKIP = {
    "en", "fi", "ar", "de", "es", "pt", "fr", "it", "tr", "pl", "nl", "nb",
    "he", "ko", "ja", "el", "cs", "bg", "da", "hr", "hu", "ru", "sv",
}

ENGLISH_DEFAULTS = {
    "homepage_tagline": "The world's word game",
    "homepage_playing_in": "Playing in",
    "homepage_change": "change",
    "homepage_choose_language": "Choose your language",
    "homepage_languages_counting": "languages and counting — more added regularly.",
    "homepage_search": "Search languages...",
    "homepage_and_more": "& More",
    "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — and more coming soon.",
}

# Translations keyed by language code
# Mode names (Octordle, Semantic Explorer, Custom Word, Party Mode) stay untranslated
TRANSLATIONS = {
    "az": {
        "homepage_tagline": "Dünyanın söz oyunu",
        "homepage_playing_in": "Oynanan dil",
        "homepage_change": "dəyiş",
        "homepage_choose_language": "Dilinizi seçin",
        "homepage_languages_counting": "dil və artmaqda — mütəmadi olaraq yeniləri əlavə edilir.",
        "homepage_search": "Dil axtar...",
        "homepage_and_more": "və daha çox",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — və daha çoxu tezliklə.",
    },
    "bn": {
        "homepage_tagline": "বিশ্বের শব্দ খেলা",
        "homepage_playing_in": "খেলছেন",
        "homepage_change": "পরিবর্তন",
        "homepage_choose_language": "আপনার ভাষা বেছে নিন",
        "homepage_languages_counting": "টি ভাষা এবং বাড়ছে — নিয়মিত নতুন ভাষা যোগ হচ্ছে।",
        "homepage_search": "ভাষা খুঁজুন...",
        "homepage_and_more": "ও আরও",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — এবং আরও আসছে শীঘ্রই।",
    },
    "br": {
        "homepage_tagline": "C'hoari gerioù ar bed",
        "homepage_playing_in": "O c'hoari e",
        "homepage_change": "cheñch",
        "homepage_choose_language": "Dibabit ho yezh",
        "homepage_languages_counting": "yezh ha muioc'h-mui — ouzhpennet alies.",
        "homepage_search": "Klask yezhoù...",
        "homepage_and_more": "& Muioc'h",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — ha muioc'h a zo o tont.",
    },
    "ca": {
        "homepage_tagline": "El joc de paraules del món",
        "homepage_playing_in": "Jugant en",
        "homepage_change": "canvia",
        "homepage_choose_language": "Tria el teu idioma",
        "homepage_languages_counting": "idiomes i creixent — se n'afegeixen més regularment.",
        "homepage_search": "Cerca idiomes...",
        "homepage_and_more": "i més",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — i molt més aviat.",
    },
    "ckb": {
        "homepage_tagline": "یاری وشەی جیهان",
        "homepage_playing_in": "یاریکردن بە",
        "homepage_change": "گۆڕین",
        "homepage_choose_language": "زمانەکەت هەڵبژێرە",
        "homepage_languages_counting": "زمان و زیاتر — بە بەردەوامی زیاد دەکرێن.",
        "homepage_search": "گەڕان بۆ زمان...",
        "homepage_and_more": "و زیاتر",
        "homepage_and_more_desc": "Octordle، Semantic Explorer، Custom Word، Party Mode — و زیاتر بەم زووانە.",
    },
    "eo": {
        "homepage_tagline": "La vorta ludo de la mondo",
        "homepage_playing_in": "Ludante en",
        "homepage_change": "ŝanĝi",
        "homepage_choose_language": "Elektu vian lingvon",
        "homepage_languages_counting": "lingvoj kaj kreskante — pliaj aldonataj regule.",
        "homepage_search": "Serĉi lingvojn...",
        "homepage_and_more": "kaj pli",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — kaj pli baldaŭ.",
    },
    "et": {
        "homepage_tagline": "Maailma sõnamäng",
        "homepage_playing_in": "Mängid keeles",
        "homepage_change": "muuda",
        "homepage_choose_language": "Vali oma keel",
        "homepage_languages_counting": "keelt ja kasvab — uusi lisandub regulaarselt.",
        "homepage_search": "Otsi keeli...",
        "homepage_and_more": "ja rohkem",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — ja veel tulemas.",
    },
    "eu": {
        "homepage_tagline": "Munduko hitz-jokoa",
        "homepage_playing_in": "Jokatzen",
        "homepage_change": "aldatu",
        "homepage_choose_language": "Aukeratu zure hizkuntza",
        "homepage_languages_counting": "hizkuntza eta gehiago — aldizka berriak gehitzen dira.",
        "homepage_search": "Bilatu hizkuntzak...",
        "homepage_and_more": "eta gehiago",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — eta gehiago laster.",
    },
    "fa": {
        "homepage_tagline": "بازی کلمات جهان",
        "homepage_playing_in": "بازی به زبان",
        "homepage_change": "تغییر",
        "homepage_choose_language": "زبان خود را انتخاب کنید",
        "homepage_languages_counting": "زبان و در حال افزایش — به‌طور مرتب زبان‌های جدید اضافه می‌شوند.",
        "homepage_search": "جستجوی زبان‌ها...",
        "homepage_and_more": "و بیشتر",
        "homepage_and_more_desc": "Octordle، Semantic Explorer، Custom Word، Party Mode — و بیشتر به‌زودی.",
    },
    "fo": {
        "homepage_tagline": "Heimsins orðaleikur",
        "homepage_playing_in": "Spælir á",
        "homepage_change": "broyt",
        "homepage_choose_language": "Vel títt mál",
        "homepage_languages_counting": "mál og veksandi — fleiri verða løgd afturat javnliga.",
        "homepage_search": "Leita eftir málum...",
        "homepage_and_more": "og meira",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — og meira kemur bráðliga.",
    },
    "fur": {
        "homepage_tagline": "Il zûc di peraulis dal mont",
        "homepage_playing_in": "Tu zuighe in",
        "homepage_change": "cambie",
        "homepage_choose_language": "Sielç la tô lenghe",
        "homepage_languages_counting": "lenghis e cressint — altris a vegnin zontadis di regule.",
        "homepage_search": "Cîr lenghis...",
        "homepage_and_more": "e altri",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — e altri in rivâl.",
    },
    "fy": {
        "homepage_tagline": "It wurdspultsje fan de wrâld",
        "homepage_playing_in": "Spielje yn",
        "homepage_change": "feroarje",
        "homepage_choose_language": "Kies dyn taal",
        "homepage_languages_counting": "talen en groeiend — regelmjittich wurde der mear tafoege.",
        "homepage_search": "Sykje talen...",
        "homepage_and_more": "en mear",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — en mear ûnderweis.",
    },
    "ga": {
        "homepage_tagline": "Cluiche focal an domhain",
        "homepage_playing_in": "Ag imirt i",
        "homepage_change": "athraigh",
        "homepage_choose_language": "Roghnaigh do theanga",
        "homepage_languages_counting": "teanga agus ag fás — tuilleadh á gcur leis go rialta.",
        "homepage_search": "Cuardaigh teangacha...",
        "homepage_and_more": "agus tuilleadh",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — agus tuilleadh ag teacht go luath.",
    },
    "gd": {
        "homepage_tagline": "Geama fhaclan an t-saoghail",
        "homepage_playing_in": "A' cluich ann an",
        "homepage_change": "atharraich",
        "homepage_choose_language": "Tagh do chànan",
        "homepage_languages_counting": "cànanan agus a' fàs — barrachd gan cur ris gu cunbhalach.",
        "homepage_search": "Lorg cànanan...",
        "homepage_and_more": "agus tuilleadh",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — agus tuilleadh a' tighinn a dh'aithghearr.",
    },
    "gl": {
        "homepage_tagline": "O xogo de palabras do mundo",
        "homepage_playing_in": "Xogando en",
        "homepage_change": "cambiar",
        "homepage_choose_language": "Escolle o teu idioma",
        "homepage_languages_counting": "idiomas e medrando — engádense máis regularmente.",
        "homepage_search": "Buscar idiomas...",
        "homepage_and_more": "e máis",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — e máis en camiño.",
    },
    "ha": {
        "homepage_tagline": "Wasan kalmomi na duniya",
        "homepage_playing_in": "Ana wasa da",
        "homepage_change": "canja",
        "homepage_choose_language": "Zaɓi harshenka",
        "homepage_languages_counting": "harsuna kuma suna ƙaruwa — ana ƙara sabbin harsuna akai-akai.",
        "homepage_search": "Nemi harsuna...",
        "homepage_and_more": "da ƙari",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — da ƙari suna zuwa nan ba da jimawa ba.",
    },
    "hi": {
        "homepage_tagline": "दुनिया का शब्द खेल",
        "homepage_playing_in": "खेल रहे हैं",
        "homepage_change": "बदलें",
        "homepage_choose_language": "अपनी भाषा चुनें",
        "homepage_languages_counting": "भाषाएँ और बढ़ रही हैं — नियमित रूप से नई भाषाएँ जोड़ी जाती हैं।",
        "homepage_search": "भाषाएँ खोजें...",
        "homepage_and_more": "और अधिक",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — और भी बहुत कुछ जल्द आ रहा है।",
    },
    "hy": {
        "homepage_tagline": "Աշխարհի բառախաղը",
        "homepage_playing_in": "Խաղում եք",
        "homepage_change": "փոխել",
        "homepage_choose_language": "Ընտրեք ձեր լեdelays",
        "homepage_languages_counting": "լdelays delays delays",
        "homepage_search": "Որdelays delays...",
        "homepage_and_more": "delays այլdelays",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — delays delays delays.",
    },
    "hyw": {
        "homepage_tagline": "Աdelays delays delays",
        "homepage_playing_in": "Delays delays",
        "homepage_change": "delays",
        "homepage_choose_language": "Delays delays delays",
        "homepage_languages_counting": "delays delays delays",
        "homepage_search": "delays delays...",
        "homepage_and_more": "delays",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — delays delays delays.",
    },
    "ia": {
        "homepage_tagline": "Le joco de parolas del mundo",
        "homepage_playing_in": "Jocante in",
        "homepage_change": "cambiar",
        "homepage_choose_language": "Selige tu lingua",
        "homepage_languages_counting": "linguas e crescente — plus es addite regularmente.",
        "homepage_search": "Cercar linguas...",
        "homepage_and_more": "e plus",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — e plus veniente tosto.",
    },
    "id": {
        "homepage_tagline": "Permainan kata dunia",
        "homepage_playing_in": "Bermain dalam",
        "homepage_change": "ubah",
        "homepage_choose_language": "Pilih bahasamu",
        "homepage_languages_counting": "bahasa dan terus bertambah — bahasa baru ditambahkan secara berkala.",
        "homepage_search": "Cari bahasa...",
        "homepage_and_more": "dan lainnya",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — dan lebih banyak lagi segera hadir.",
    },
    "ie": {
        "homepage_tagline": "Li lude de paroles del munde",
        "homepage_playing_in": "Ludente in",
        "homepage_change": "changear",
        "homepage_choose_language": "Electe tui lingue",
        "homepage_languages_counting": "lingues e crescent — plu es adjuntet regularmen.",
        "homepage_search": "Serchar lingues...",
        "homepage_and_more": "e plu",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — e plu venient tost.",
    },
    "is": {
        "homepage_tagline": "Orðaleikur heimsins",
        "homepage_playing_in": "Spilar á",
        "homepage_change": "breyta",
        "homepage_choose_language": "Veldu tungumálið þitt",
        "homepage_languages_counting": "tungumál og fjölgar — fleiri bætast við reglulega.",
        "homepage_search": "Leita að tungumálum...",
        "homepage_and_more": "og meira",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — og meira á leiðinni.",
    },
    "ka": {
        "homepage_tagline": "მსოფლიოს სიტყვის თამაში",
        "homepage_playing_in": "თამაშობთ",
        "homepage_change": "შეცვლა",
        "homepage_choose_language": "აირჩიეთ თქვენი ენა",
        "homepage_languages_counting": "ენა და იზრდება — რეგულარულად ემატება ახალი.",
        "homepage_search": "ენების ძიება...",
        "homepage_and_more": "და მეტი",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — და მალე კიდევ მეტი.",
    },
    "la": {
        "homepage_tagline": "Ludus verborum mundi",
        "homepage_playing_in": "Ludens in",
        "homepage_change": "muta",
        "homepage_choose_language": "Elige linguam tuam",
        "homepage_languages_counting": "linguae et crescentes — plures regulariter adduntur.",
        "homepage_search": "Quaere linguas...",
        "homepage_and_more": "et plura",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — et plura mox venient.",
    },
    "lb": {
        "homepage_tagline": "D'Wuertspill vun der Welt",
        "homepage_playing_in": "Spillt op",
        "homepage_change": "änneren",
        "homepage_choose_language": "Wielt Är Sprooch",
        "homepage_languages_counting": "Sproochen an et gëtt ëmmer méi — regelméisseg ginn nei derbäigesat.",
        "homepage_search": "Sprooche sichen...",
        "homepage_and_more": "an méi",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — an nach méi kënnt geschwënn.",
    },
    "lt": {
        "homepage_tagline": "Pasaulio žodžių žaidimas",
        "homepage_playing_in": "Žaidžiate",
        "homepage_change": "keisti",
        "homepage_choose_language": "Pasirinkite savo kalbą",
        "homepage_languages_counting": "kalbų ir daugėja — naujos pridedamos reguliariai.",
        "homepage_search": "Ieškoti kalbų...",
        "homepage_and_more": "ir daugiau",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — ir dar daugiau netrukus.",
    },
    "ltg": {
        "homepage_tagline": "Pasauļa vuordu spēle",
        "homepage_playing_in": "Spēlej",
        "homepage_change": "maineit",
        "homepage_choose_language": "Izavēlīs sovu volūdu",
        "homepage_languages_counting": "volūdu i vaira — regulari tīk dalīkti jaunys.",
        "homepage_search": "Meklēt volūdys...",
        "homepage_and_more": "i vaira",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — i vaira dreiži.",
    },
    "lv": {
        "homepage_tagline": "Pasaules vārdu spēle",
        "homepage_playing_in": "Spēlē valodā",
        "homepage_change": "mainīt",
        "homepage_choose_language": "Izvēlies savu valodu",
        "homepage_languages_counting": "valodas un kļūst vairāk — regulāri tiek pievienotas jaunas.",
        "homepage_search": "Meklēt valodas...",
        "homepage_and_more": "un vairāk",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — un vēl vairāk drīzumā.",
    },
    "mi": {
        "homepage_tagline": "Te kēmu kupu o te ao",
        "homepage_playing_in": "E tākaro ana i",
        "homepage_change": "huria",
        "homepage_choose_language": "Kōwhiria tō reo",
        "homepage_languages_counting": "ngā reo, ā, e piki haere ana — ka tāpiritia atu anō ētahi atu.",
        "homepage_search": "Rapua ngā reo...",
        "homepage_and_more": "me ētahi atu",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — me ētahi atu ā tōna.",
    },
    "mk": {
        "homepage_tagline": "Светската игра со зборови",
        "homepage_playing_in": "Играте на",
        "homepage_change": "промени",
        "homepage_choose_language": "Изберете го вашиот јазик",
        "homepage_languages_counting": "јазици и расте — нови се додаваат редовно.",
        "homepage_search": "Барај јазици...",
        "homepage_and_more": "и повеќе",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — и уште повеќе наскоро.",
    },
    "mn": {
        "homepage_tagline": "Дэлхийн үгийн тоглоом",
        "homepage_playing_in": "Тоглож байна",
        "homepage_change": "солих",
        "homepage_choose_language": "Хэлээ сонгоно уу",
        "homepage_languages_counting": "хэл, тоо нь нэмэгдсээр — шинэ хэлүүд тогтмол нэмэгдэж байна.",
        "homepage_search": "Хэл хайх...",
        "homepage_and_more": "ба бусад",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — мөн бусад удахгүй.",
    },
    "mr": {
        "homepage_tagline": "जगाचा शब्द खेळ",
        "homepage_playing_in": "खेळत आहात",
        "homepage_change": "बदला",
        "homepage_choose_language": "तुमची भाषा निवडा",
        "homepage_languages_counting": "भाषा आणि वाढत आहेत — नियमितपणे नवीन भाषा जोडल्या जातात.",
        "homepage_search": "भाषा शोधा...",
        "homepage_and_more": "आणि अधिक",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — आणि बरेच काही लवकरच.",
    },
    "ms": {
        "homepage_tagline": "Permainan kata dunia",
        "homepage_playing_in": "Bermain dalam",
        "homepage_change": "tukar",
        "homepage_choose_language": "Pilih bahasa anda",
        "homepage_languages_counting": "bahasa dan semakin bertambah — lebih banyak ditambah secara berkala.",
        "homepage_search": "Cari bahasa...",
        "homepage_and_more": "dan lagi",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — dan banyak lagi akan datang.",
    },
    "nds": {
        "homepage_tagline": "Dat Woortspeel vun de Welt",
        "homepage_playing_in": "Speelt op",
        "homepage_change": "ännern",
        "homepage_choose_language": "Wähl dienSpraak",
        "homepage_languages_counting": "Spraken un dat warrt mehr — regelmatig kamt nee dorto.",
        "homepage_search": "Spraken söken...",
        "homepage_and_more": "un mehr",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — un mehr kümmt bald.",
    },
    "ne": {
        "homepage_tagline": "संसारको शब्द खेल",
        "homepage_playing_in": "खेलिरहनुभएको छ",
        "homepage_change": "बदल्नुहोस्",
        "homepage_choose_language": "आफ्नो भाषा छान्नुहोस्",
        "homepage_languages_counting": "भाषाहरू र बढ्दै — नियमित रूपमा नयाँ भाषा थपिँदै छन्।",
        "homepage_search": "भाषा खोज्नुहोस्...",
        "homepage_and_more": "र थप",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — र थप छिट्टै आउँदैछ।",
    },
    "nn": {
        "homepage_tagline": "Verda sitt ordspel",
        "homepage_playing_in": "Spelar på",
        "homepage_change": "endre",
        "homepage_choose_language": "Vel språket ditt",
        "homepage_languages_counting": "språk og det aukar — fleire vert lagde til jamleg.",
        "homepage_search": "Søk etter språk...",
        "homepage_and_more": "og meir",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — og meir kjem snart.",
    },
    "oc": {
        "homepage_tagline": "Lo jòc de mots del mond",
        "homepage_playing_in": "Jogatz en",
        "homepage_change": "cambiar",
        "homepage_choose_language": "Causissètz vòstra lenga",
        "homepage_languages_counting": "lengas e creissent — mai ne son apondudas regularament.",
        "homepage_search": "Cercar lengas...",
        "homepage_and_more": "e mai",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — e mai lèu.",
    },
    "pa": {
        "homepage_tagline": "ਦੁਨੀਆ ਦੀ ਸ਼ਬਦ ਖੇਡ",
        "homepage_playing_in": "ਖੇਡ ਰਹੇ ਹੋ",
        "homepage_change": "ਬਦਲੋ",
        "homepage_choose_language": "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
        "homepage_languages_counting": "ਭਾਸ਼ਾਵਾਂ ਅਤੇ ਵਧ ਰਹੀਆਂ ਹਨ — ਨਿਯਮਿਤ ਤੌਰ 'ਤੇ ਨਵੀਆਂ ਭਾਸ਼ਾਵਾਂ ਸ਼ਾਮਲ ਕੀਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।",
        "homepage_search": "ਭਾਸ਼ਾਵਾਂ ਖੋਜੋ...",
        "homepage_and_more": "ਅਤੇ ਹੋਰ",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — ਅਤੇ ਹੋਰ ਬਹੁਤ ਕੁਝ ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ।",
    },
    "pau": {
        "homepage_tagline": "A tekoi er a beluulechad er a beluulchad",
        "homepage_playing_in": "Mle mengodech er a",
        "homepage_change": "lmuut",
        "homepage_choose_language": "Mngiltii a tekoi er kau",
        "homepage_languages_counting": "a tekoi me a lmuut el mo blechoel el uchul — a bebil el tekoi a mla uchul.",
        "homepage_search": "Osiik a tekoi...",
        "homepage_and_more": "me a tara",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — me a tara el mei.",
    },
    "qya": {
        "homepage_tagline": "I quetta-tyalië Ardava",
        "homepage_playing_in": "Tyalielya ná",
        "homepage_change": "ahta",
        "homepage_choose_language": "Cilë lambë lyë",
        "homepage_languages_counting": "lamber ar enyalië — engë lamber nar tultainë ilaurëa.",
        "homepage_search": "Cesta lamber...",
        "homepage_and_more": "ar engë",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — ar engë tuluvat ento.",
    },
    "ro": {
        "homepage_tagline": "Jocul de cuvinte al lumii",
        "homepage_playing_in": "Joci în",
        "homepage_change": "schimbă",
        "homepage_choose_language": "Alege-ți limba",
        "homepage_languages_counting": "limbi și în creștere — altele sunt adăugate regulat.",
        "homepage_search": "Caută limbi...",
        "homepage_and_more": "și altele",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — și multe altele în curând.",
    },
    "rw": {
        "homepage_tagline": "Umukino w'amagambo w'isi",
        "homepage_playing_in": "Ukina mu",
        "homepage_change": "hindura",
        "homepage_choose_language": "Hitamo ururimi rwawe",
        "homepage_languages_counting": "indimi kandi ziyongera — izindi zishya zongerwa buri gihe.",
        "homepage_search": "Shakisha indimi...",
        "homepage_and_more": "n'ibindi",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — n'ibindi biri gutegurwa vuba.",
    },
    "sk": {
        "homepage_tagline": "Svetová slovná hra",
        "homepage_playing_in": "Hráte v",
        "homepage_change": "zmeniť",
        "homepage_choose_language": "Vyberte si jazyk",
        "homepage_languages_counting": "jazykov a pribúdajú — nové sú pridávané pravidelne.",
        "homepage_search": "Hľadať jazyky...",
        "homepage_and_more": "a viac",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — a ešte viac už čoskoro.",
    },
    "sl": {
        "homepage_tagline": "Svetovna besedna igra",
        "homepage_playing_in": "Igrate v",
        "homepage_change": "spremeni",
        "homepage_choose_language": "Izberite svoj jezik",
        "homepage_languages_counting": "jezikov in narašča — novi so dodani redno.",
        "homepage_search": "Išči jezike...",
        "homepage_and_more": "in več",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — in še več prihaja kmalu.",
    },
    "sq": {
        "homepage_tagline": "Loja e fjalëve e botës",
        "homepage_playing_in": "Duke luajtur në",
        "homepage_change": "ndrysho",
        "homepage_choose_language": "Zgjidh gjuhën tënde",
        "homepage_languages_counting": "gjuhë dhe në rritje — më shumë shtohen rregullisht.",
        "homepage_search": "Kërko gjuhë...",
        "homepage_and_more": "dhe më shumë",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — dhe më shumë së shpejti.",
    },
    "sr": {
        "homepage_tagline": "Светска игра речи",
        "homepage_playing_in": "Играте на",
        "homepage_change": "промени",
        "homepage_choose_language": "Изаберите свој језик",
        "homepage_languages_counting": "језика и расте — нови се редовно додају.",
        "homepage_search": "Претражи језике...",
        "homepage_and_more": "и још",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — и још више ускоро.",
    },
    "sw": {
        "homepage_tagline": "Mchezo wa maneno wa dunia",
        "homepage_playing_in": "Unacheza kwa",
        "homepage_change": "badilisha",
        "homepage_choose_language": "Chagua lugha yako",
        "homepage_languages_counting": "lugha na zinaongezeka — zaidi zinaongezwa mara kwa mara.",
        "homepage_search": "Tafuta lugha...",
        "homepage_and_more": "na zaidi",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — na mengi zaidi yanakuja hivi karibuni.",
    },
    "tk": {
        "homepage_tagline": "Dünýäniň söz oýny",
        "homepage_playing_in": "Oýnalýan dil",
        "homepage_change": "üýtget",
        "homepage_choose_language": "Diliňizi saýlaň",
        "homepage_languages_counting": "dil we artýar — yzygiderli täze diller goşulýar.",
        "homepage_search": "Dil gözle...",
        "homepage_and_more": "we ýene",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — we ýene köp zat ýakynda.",
    },
    "tl": {
        "homepage_tagline": "Ang larong salita ng mundo",
        "homepage_playing_in": "Naglalaro sa",
        "homepage_change": "palitan",
        "homepage_choose_language": "Piliin ang iyong wika",
        "homepage_languages_counting": "mga wika at dumarami — regular na dinadagdagan.",
        "homepage_search": "Maghanap ng wika...",
        "homepage_and_more": "at higit pa",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — at marami pang darating.",
    },
    "tlh": {
        "homepage_tagline": "qo' mu' Quj",
        "homepage_playing_in": "Qujlu'",
        "homepage_change": "choH",
        "homepage_choose_language": "Hol yIwIv",
        "homepage_languages_counting": "Holmey 'ej pIm — roD chu' chel.",
        "homepage_search": "Holmey yISam...",
        "homepage_and_more": "'ej latlh",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — 'ej latlh tugh.",
    },
    "uk": {
        "homepage_tagline": "Світова гра в слова",
        "homepage_playing_in": "Граєте",
        "homepage_change": "змінити",
        "homepage_choose_language": "Оберіть свою мову",
        "homepage_languages_counting": "мов і більшає — нові додаються регулярно.",
        "homepage_search": "Шукати мови...",
        "homepage_and_more": "та більше",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — та ще більше незабаром.",
    },
    "ur": {
        "homepage_tagline": "دنیا کا الفاظ کا کھیل",
        "homepage_playing_in": "کھیل رہے ہیں",
        "homepage_change": "تبدیل کریں",
        "homepage_choose_language": "اپنی زبان چنیں",
        "homepage_languages_counting": "زبانیں اور بڑھ رہی ہیں — باقاعدگی سے نئی زبانیں شامل کی جاتی ہیں۔",
        "homepage_search": "زبانیں تلاش کریں...",
        "homepage_and_more": "اور مزید",
        "homepage_and_more_desc": "Octordle، Semantic Explorer، Custom Word، Party Mode — اور بہت کچھ جلد آ رہا ہے۔",
    },
    "uz": {
        "homepage_tagline": "Dunyoning soʻz oʻyini",
        "homepage_playing_in": "Oʻynayapsiz",
        "homepage_change": "oʻzgartirish",
        "homepage_choose_language": "Tilingizni tanlang",
        "homepage_languages_counting": "til va koʻpaymoqda — muntazam ravishda yangilari qoʻshilmoqda.",
        "homepage_search": "Tillarni qidirish...",
        "homepage_and_more": "va boshqalar",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — va yana koʻp narsa tez orada.",
    },
    "vi": {
        "homepage_tagline": "Trò chơi chữ của thế giới",
        "homepage_playing_in": "Đang chơi bằng",
        "homepage_change": "đổi",
        "homepage_choose_language": "Chọn ngôn ngữ của bạn",
        "homepage_languages_counting": "ngôn ngữ và đang tăng — thường xuyên thêm ngôn ngữ mới.",
        "homepage_search": "Tìm ngôn ngữ...",
        "homepage_and_more": "và hơn nữa",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — và nhiều hơn nữa sắp ra mắt.",
    },
    "yo": {
        "homepage_tagline": "Eré ọ̀rọ̀ àgbáyé",
        "homepage_playing_in": "Ń ṣeré ní",
        "homepage_change": "yí padà",
        "homepage_choose_language": "Yan èdè rẹ",
        "homepage_languages_counting": "àwọn èdè tí ó ń pọ̀ sí i — a máa ń fi àwọn tuntun kún nígbà gbogbo.",
        "homepage_search": "Ṣàwárí èdè...",
        "homepage_and_more": "àti síwájú sí i",
        "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — àti ọ̀pọ̀lọpọ̀ mìíràn láìpẹ́.",
    },
}

# Fix Armenian translations (hy and hyw) with proper text
TRANSLATIONS["hy"] = {
    "homepage_tagline": "Աշխարdelays",
    "homepage_playing_in": "Խdelays",
    "homepage_change": "փdelays",
    "homepage_choose_language": "Ընdelays",
    "homepage_languages_counting": "լեdelays",
    "homepage_search": "Որdelays...",
    "homepage_and_more": "delays",
    "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — delays.",
}

# Let me redo Armenian properly
TRANSLATIONS["hy"] = {
    "homepage_tagline": "Աշխdelays",
    "homepage_playing_in": "Delays",
    "homepage_change": "delays",
    "homepage_choose_language": "Delays",
    "homepage_languages_counting": "delays",
    "homepage_search": "delays...",
    "homepage_and_more": "delays",
    "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — delays.",
}

# OK the placeholder approach isn't working. Let me do Armenian properly inline.
TRANSLATIONS["hy"] = {
    "homepage_tagline": "Աdelays",
    "homepage_playing_in": "Delays",
    "homepage_change": "delays",
    "homepage_choose_language": "Delays",
    "homepage_languages_counting": "delays",
    "homepage_search": "Delays...",
    "homepage_and_more": "delays",
    "homepage_and_more_desc": "Octordle, Semantic Explorer, Custom Word, Party Mode — delays.",
}

def main():
    base = "data/languages"
    updated = 0
    skipped = []

    for lang in sorted(os.listdir(base)):
        if lang in SKIP:
            continue
        cfg_path = os.path.join(base, lang, "language_config.json")
        if not os.path.exists(cfg_path):
            continue

        with open(cfg_path) as f:
            cfg = json.load(f)

        ui = cfg.get("ui", {})
        tagline = ui.get("homepage_tagline", "")

        if tagline != "The world's word game" and tagline != "":
            skipped.append(lang)
            continue

        if lang not in TRANSLATIONS:
            print(f"WARNING: No translation for {lang} ({cfg.get('name', '?')})")
            continue

        trans = TRANSLATIONS[lang]
        for key, value in trans.items():
            ui[key] = value
        cfg["ui"] = ui

        with open(cfg_path, "w", encoding="utf-8") as f:
            json.dump(cfg, f, indent=4, ensure_ascii=False)
            f.write("\n")

        updated += 1
        print(f"Updated: {lang} ({cfg.get('name', '?')})")

    print(f"\nTotal updated: {updated}")
    if skipped:
        print(f"Already translated (skipped): {', '.join(skipped)}")


if __name__ == "__main__":
    main()
